apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend              # ⬅️ HARUS sama dengan base
  namespace: rahasia-dapur
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend              # ⬅️ HARUS sama dengan base
  namespace: rahasia-dapur
spec:
  replicas: 2