apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: rahasia-dapur
type: Opaque
stringData:
  MONGO_URI: "mongodb://mongodb:27017/rahasia_dapur"
  JWT_ACCESS_SECRET: "replace-me"
  JWT_REFRESH_SECRET: "replace-me"
  CLOUDINARY_CLOUD_NAME: "replace-me"
  CLOUDINARY_API_KEY: "replace-me"
  CLOUDINARY_API_SECRET: "replace-me"