resources:
  - namespace.yaml
  - backend-configmap.yaml
  - backend-secret.yaml
  - mongodb-deployment.yaml
  - mongodb-service.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml