resources:
  - namespace.yaml
  - backend-configmap.yaml
  - backend-secret.yaml
  - mongo-deployment.yaml
  - mongo-service.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml